### ISSUE TITLE
Feedback: war gedrückter Button korrekt/falsch?

### ISSUE THREAD

**Issue by kathrin77** [kathrin77/QuickPic#5]
irgendein Feedback, ob der gedrückte Button korrekt war oder nicht (ausser in der winzigen tvPoints sieht man das nicht) --> Button sollte kurz aufleuchten (z.B. rot wenn falsch, grün wenn korrekt).  

kh: Es muss irgendwie mit einem Runnable gehen, ähnlich wie beim Simon-Game.

tn: beim ersten Googeln bin ich auf diese Frage bei stackoverflow gestoßen:
https://stackoverflow.com/questions/38377823/quiz-app-change-button-color-of-wrong-and-correct-answer-on-wrong-answer-select

**Comment by kathrin77** [comment]
Erster Schritt: der gedrückte Button soll farbig aufleuchten (rot/grün)
Zweiter Schritt (vielleicht): wenn der gedrückte Button falsch war, soll der korrekte Button auch noch grün aufleuchten (--> Lerneffekt fürs nächste Spiel).

**Comment by tn86** [comment]
Erster Schritt ist umgesetzt

**Comment by tn86** [comment]
Zweiter Schritt auch umgesetzt.
