### ISSUE TITLE
Timer implementieren

### ISSUE THREAD

**Issue by kathrin77** [kathrin77/QuickPic#7]
Der Timer existiert noch gar nicht, ausser ein angedachtes Layout.

**Comment by kathrin77** [comment]
1) Vorgehen aus SimonGame anschauen, evtl. übernehmen
2) Erster Schritt: Timer anzeigen Textview
3) nice to have: Timer anzeigen grafisch (Balken o.ä.)
4) Timer soll sich verkürzen mit jeder Runde --> es braucht einen Algorithmus dazu.

**Comment by tn86** [comment]
Man hat jetzt am Anfang 10 Sekunden Zeit und pro neuer Frage wird es eine halbe Sekunde weniger. Die für die aktuelle Frage insgesamt zur Verfügung stehende Zeit in Millisekunden wird in der TextView unten rechts eingeblendet.
Es gibt aber noch ein Problem: Wenn man drei Fragen falsch beantwortet hat, kommt GameOver. Kurz danach kommt wieder GameOver. Ich habe noch nicht herausgefunden, wie ich das verhindern kann. Ich habe schon an allen möglichen Stellen "timeoutHandler.removeCallbacksAndMessages(null);" eingebracht, aber es hat alles nichts gebracht.

**Comment by tn86** [comment]
Problem mit dem zweiten Game Over bei drei falschen Antworten ist gelöst.

**Comment by kathrin77** [comment]
Ich bin gerade dabei, den Timer noch grafisch mit einem Balken anzuzeigen. Bisher ohne Erfolg, arbeite aber noch dran.

**Comment by kathrin77** [comment]
Update: ein erster Versuch ist implementiert. Der Timer-Balken passt sich nun dem timeout (MILLIS) an. Momentan noch statische Pixelwerte --> mit versch. Bildschirmgrössen testen.
tvTime: evtl. in Sekunden anzeigen oder weglassen?
