### ISSUE TITLE
Bestenliste anlegen

### ISSUE THREAD

**Issue by kathrin77** [kathrin77/QuickPic#9]
auf der HighscoreAcitivity:

Bestenliste zum Eintragen, Bestenliste anzeigen (Erreichte Punkte).

**Comment by kathrin77** [comment]
Siehe Buch Uwe Post, Kapitel 7

**Comment by tn86** [comment]
Man kann nun bei Erreichen eines Highscores seinen Namen eingeben und zusammen mit dem Highscore abspeichern. Im Buch wird eine Liste von Highscores nur mit einer Speicherung im Internet verbunden. Eine Top-3-Liste könnte man vielleicht auch mit den SharedPreferences umsetzen mit 3 Schlüsseln für Top-1, Top-2, Top-3, die sich dann ersetzen.

**Comment by tn86** [comment]
Top-3-Liste umgesetzt. Man sollte sich das Verhalten bei gleichem Punktestand wie jemand in Top-3 nochmal anschauen. Layout könnte noch verschönert werden.

**Comment by kathrin77** [comment]
Der Text sollte noch ein bisschen angepasst werden (es ist ja nicht immer der beste highscore, sondern "nur" top-3.
Ansonsten funktioniert es bestens, soweit ich sehe. Können wir am Schluss (mit evtl. Verschönerung) noch anschauen.

**Comment by kathrin77** [comment]
es wäre vielleicht auch nett, zu wissen, wann man den Höchstpunktestand erreicht hat. Das könnte man ganz einfach halten mit einer fixen Textview, oder einer Variable, die sich aus der answer.length automatisch generiert und einfach irgendwo noch angezeigt wird ("Maximum possible Points: ..." oder so). Nur wenn noch Zeit.
